services:
  os:
    container_name: almaLinux
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: devOS
      args:
        user: $USER
        pass: $PASS
    privileged: true
    restart: always
    env_file: ./.env
    ports:
      - "53:53"
      - "8008:8008"
    depends_on:
      - server
    networks:
      - os-server

  server:
    container_name: node
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: devServer
      args:
        user: $USER
        pass: $PASS
    privileged: true
    restart: always
    env_file: ./.env
    ports:
      - "3000:3000"
    volumes:
      -  ./packages:/usr/src/app/packages
    depends_on:
      - mongodb
    networks:
      - express-mongo
      - os-server

  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$USER
      - MONGO_INITDB_ROOT_PASSWORD=$PASS
    expose:
      - 27018
    volumes:
       - ./data:/data/db
    networks:
      - express-mongo

networks:
  express-mongo:
  os-server:
